name: ci

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os:
        - macos-15
        - ubuntu-24.04
        - windows-2025
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Node version defined in manifest
        uses: volta-cli/action@v4
      - name: Install Node dependencies
        run: npm ci
      - name: Run Node tests
        run: npm t

